version: '3.8'

services:
  db:
    container_name: holocene_db
    image: postgres:latest
    environment:
      POSTGRES_DB: holocene
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - holocene_network

  app:
    container_name: holocene_app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - holocene_network
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: secret
      DB_DATABASE: holocene

volumes:
  postgres_data:

networks:
  holocene_network:
    driver: bridge
